services:
  web:
    build:
      context: .
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: node dist/server/index.js

  db:
    image: pgvector/pgvector:pg17
    ports:
      - '5432:5432'
    env_file: .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
